### ISSUE TITLE
Calling close() on EventSource object on client side (browser) does not get handled as closing http connection on server side

### ISSUE THREAD

**Issue by wkozaczuk** [hseeberger/akka-sse#12]
It should lead to Cancelled event on publisher actor side. Trying to push events after EventSource.close() eventually lead to Broken pipe TcpClose event

**Comment by hseeberger** [comment]
Thanks for reporting, very interesting, as we are currently investigating another issue which might be related.

Could you please provide a little more context:
- Where are you calling the close() method? On the JavaScript EventSource object?
- Do you have a reproducible test case?

**Comment by wkozaczuk** [comment]
Yes it is on the JavaScript EventSource object. 

If EventSource.close() is equivalent to closing the HTTP connection I should be able to provide a test.

**Comment by huntc** [comment]
#13 confirms that the issue may be higher up in the stack. I think that the issue should be closed here, but a new one is raised on akka-http with a reproducible test case.

**Comment by hseeberger** [comment]
@huntc, could you please provide the link to the respective issue on akka-http?

**Comment by huntc** [comment]
I've not raised one as yet - I wanted to discuss who might be able to chase it up later today.

**Comment by hseeberger** [comment]
Here's the related Akka HTTP issue: https://github.com/akka/akka/pull/16984

**Comment by drewhk** [comment]
The actual root issue is here: https://github.com/akka/akka/issues/17122

**Comment by hseeberger** [comment]
@wkozaczuk, could you please retry? Akka HTTP has moved on and this might no longer be an issue.

**Comment by hseeberger** [comment]
Closing, because no more activity.
