### ISSUE TITLE
Use a mutable data structure in ServerSentEventParser.Builder

### ISSUE THREAD

**Issue by hseeberger** [hseeberger/akka-sse#121]
Currently we use a `var` with a `Vector`, but a mutable sequence, e.g. `ListBuffer` might increase throughput.

**Comment by hseeberger** [comment]
@viktorklang, which mutable sequence do you recommend?

**Comment by viktorklang** [comment]
@hseeberger I suspect a `j.u.LinkedList` will be good enough.

**Comment by hseeberger** [comment]
Don't you think a `scala...ListBuffer` would also work?

**Comment by viktorklang** [comment]
@hseeberger I wouldn't use it but YMMV :)

**Comment by hseeberger** [comment]
@viktorklang, could you please explain? Why would a `j.u.LinkedList` be better than a `s.c.m.ListBufffer`?

**Comment by viktorklang** [comment]
@hseeberger write a JMH and see :)

**Comment by hseeberger** [comment]
@viktorklang, no spare cycles. So `j.u.LinkedList` is more performant? Do you have numbers?

**Comment by viktorklang** [comment]
@hseeberger Depends on the use case, so you'll have to JMH or trust me :)

**Comment by hseeberger** [comment]
Tried with a mutable `ListBuffer`, JMH showed no effect.

**Comment by viktorklang** [comment]
I'm not surprised, ListBuffer is not the fastest gun in the west.
