### ISSUE TITLE
Recommendation for back-pressure

### ISSUE THREAD

**Issue by cgbaker** [hseeberger/akka-sse#132]
I've got a scenario where the SSE stream that I'm subscribing to is sending too many/big messages, so that the client is disconnecting. This stream unfortunately doesn't support Last-Event-ID, so by the time that the `ServerSentEventClient` pattern has reconnected, I've missed events. I have workarounds for the issue ("let it fail"), but I'd still like to tune this to minimize the number of failures. I tried modifying the delay strategy in ServerSentEventClient, but it didn't seem to have any effect.

As an Akka novice, I was wondering if you had any advice for this (buffer size? CPU allocation? back-pressure?)

I appreciate the project, thanks a bunch!

**Comment by hseeberger** [comment]
If you can't make the server send lost events, I don't think there's anything you can do on the client. Sorry.

Can you wrap the server into something buffering events and supporting Last-Event-ID?

**Comment by cgbaker** [comment]
Do you know which tuning parameters for akka I would use to increase the amount of buffering? Without understanding these, I am afraid that any wrapper I would write would just run into the same problem. Thanks.

**Comment by hseeberger** [comment]
Please ask these questions on the Akka mailing list or Akka Gitter channel.
