### ISSUE TITLE
Deprecate Streams

### ISSUE THREAD

**Issue by hseeberger** [hseeberger/akka-sse#149]
The [`Streams.sse` pattern](https://github.com/hseeberger/akka-sse/blob/master/akka-sse/src/main/scala/de/heikoseeberger/akkasse/pattern/Streams.scala#L65) should be deprecated and eventually get removed (in version 2), because
- the actual code is just five (pretty straightforward) lines and 
- its features – except for the `onResponse` callback – are covered by `EventStreamClient`

@huntc, as the original author of this pattern, do you have an opinon (I know you have one ;-)?

**Comment by huntc** [comment]
Your call. It's a pattern because we kept using it, but we've got something higher level in the works now.

**Comment by hseeberger** [comment]
Thanks, @huntc, for you quick relply. Wrt your "higher level" thing, have you considered using `EventStreamClient` which automatically reconnects (if that's what you need)?

**Comment by huntc** [comment]
It isn't about reconnection, it is about safely soliciting state given that an event has occurred. We only solicit the state once we are sure that we are receiving events - so that we don't miss any. I can expand on this if required.
