### ISSUE TITLE
EventSource object does not reconnect in FireFox if akka-sse app gets restarted

### ISSUE THREAD

**Issue by wkozaczuk** [hseeberger/akka-sse#16]
I checked Chrome, Safari and Firefox against same akka-sse app and Chrome and Safari are able to properly re-connect after the app gets bounced. However FireFox fails to reconnect.

I was able to write simple SSE app in node.js that does equivalent logic and I was able to see all browsers including FireFox properly reconnect. So I do not think that it is FireFox bug. 

I did notice that FireBug reports reports open HTTP connection against akka-sse and node.js apps in a different way.

I wonder if it is related to the issue #12.

**Comment by hseeberger** [comment]
@wkozaczuk, could you please retry? Akka HTTP has moved on and this might no longer be an issue.

**Comment by hseeberger** [comment]
Closing, because no more activity.
