### ISSUE TITLE
ServerSentEvent.create with type does not seem to have an effect

### ISSUE THREAD

**Issue by OverlyExcessive** [hseeberger/akka-sse#174]
At least using the Java api it seems that writing for instance, `ServerSentEvent.create("foo", "bar")` will emit a SSE of type "message" instead of type "bar".

**Comment by hseeberger** [comment]
Looking at the source code and tests this seems impossible. Please provide a reproducible test.

**Comment by OverlyExcessive** [comment]
Seems that I missed something when trying locally as it works now. Apologies!

**Comment by hseeberger** [comment]
No worries 😉
