### ISSUE TITLE
ServerSentEvent.encode become private in 3.0.0

### ISSUE THREAD

**Issue by maxcom** [hseeberger/akka-sse#187]
We are using akka-sse in Play framework application, and we used this code with akka-see 2.0.0:

```
  private implicit val sseType = ContentTypeOf[ServerSentEvent](Some("text/event-stream"))

  private implicit val sseWriteable = Writeable[ServerSentEvent] { event: ServerSentEvent ⇒
    event.encode
  }

  def subscribe() = Action {
    Ok.chunked(service.subscribe())
  }
```

In 3.0.0, `encode` method become private, so we can't update to that version.

**Comment by hseeberger** [comment]
Akka SSE 3 is currently being ported to Akka HTTP. Play will be based upon Akka HTTP. Therefore there will or should be SSE support in Play in the foreseeable future. Until then please stick with Akka SSE 2.0.
