### ISSUE TITLE
How to get things from marathon /v2/event in java

### ISSUE THREAD

**Issue by lijingcsu** [hseeberger/akka-sse#188]
Dear all,
I want to write a sse client to get things from marathon /v2/event in java, 
first, i used org.glassfish.jersey.media.sse to get event-stream, but i got a 405 error, then i read the code of /v2/event, and found marathon use akka, and I read the doc of akka, but i found it's well supported in java, 
Help !

**Comment by hseeberger** [comment]
This project is EOL (see the README), please move on to Akka HTTP.
