### ISSUE TITLE
Cannot run TimeServer

### ISSUE THREAD

**Issue by rudi-cilibrasi** [hseeberger/akka-sse#53]
I seem to be able to run the TimeClient, but when I try to run 
sbt "run-main de.heikoseeberger.akkasse.example.TimeServer"
I get the following error:
java.lang.NoSuchMethodError: akka.http.scaladsl.server.RoutingSetup$.apply

I assume it is a versioning problem.  Is there any possibility of including a build/run example doc to help us out?  I have tried Scala 2.10 and 2.11 and several different ways of providing the akka jars in the lib/ directory but no luck so far.

ls lib                                       

akka-actor_2.11-2.4-SNAPSHOT.jar
akka-http-core-experimental_2.11-1.0.jar
akka-http-scala-experimental_2.11-1.0-RC2.jar
akka-stream-experimental_2.11-1.0.jar
config-1.3.0.jar

**Comment by hseeberger** [comment]
Why are you trying to set up the libraries yourself? I suggest you use sbt, like this project and the example do. Just cd into `akka-sse-example`, start two sbt sessions, each via `sbt` and then execute `run` in both, choosing the server and the client respectively.

BTW, if you want to learn about the exact dependencies, take a look into `akka-sse-example/build.sbt` and make sure to catch all transitive dependencies, e.g. via the `sbt-dependency-graph` plugin.

**Comment by rudi-cilibrasi** [comment]
That does not seem to work for me:

 % cd akka-sse-example                           scala/akka-sse (master ⚡) ipc2
 % ls                                 akka-sse/akka-sse-example (master ⚡) ipc2
build.sbt  project  src  target
 % ls                                 akka-sse/akka-sse-example (master ⚡) ipc2
build.sbt  project  src  target
 % sbt                                akka-sse/akka-sse-example (master ⚡) ipc2
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
/home/cilibrar/scala/akka-sse/akka-sse-example/build.sbt:5: error: not found: value Library
  Library.akkaHttp
  ^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by hseeberger** [comment]
Just start sbt in the root directory of the project, then change project and run the server. Repeat the same steps in a second terminal and run the client:

```
akka-sse$ sbt
[info] Loading global plugins from /Users/heiko/.sbt/0.13/plugins
[info] Loading project definition from /Users/heiko/projects/scala-projects/akka-sse/project
[info] Set current project to root (in build file:/Users/heiko/projects/scala-projects/akka-sse/)
[root]> projects
[info] In file:/Users/heiko/projects/scala-projects/akka-sse/
[info] 	   akkaSse
[info] 	   akkaSseExample
[info] 	 * root
[root]> project akkaSseExample
[info] Set current project to akka-sse-example (in build file:/Users/heiko/projects/scala-projects/akka-sse/)
[akkaSseExample]> run
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list

Multiple main classes detected, select one to run:

 [1] de.heikoseeberger.akkasse.example.TimeClient
 [2] de.heikoseeberger.akkasse.example.TimeServer
```
