### ISSUE TITLE
Publishing akka-sse for Scala 2.10

### ISSUE THREAD

**Issue by markusjura** [hseeberger/akka-sse#65]
Is it possible to publish `akka-sse 1.4.1` for Scala 2.10 as well. The library is already set with 2.10.5 as a cross compatible version. I've also published akka-sse for 2.10 locally and everything worked fine.

**Comment by hseeberger** [comment]
Done

**Comment by hseeberger** [comment]
BTW, also released 1.4.2 for Scala 2.11 and 2.10.

**Comment by markusjura** [comment]
Perfect, thanks for the quick response
