### ISSUE TITLE
MergePreferred and eagerClose with heartbeats

### ISSUE THREAD

**Issue by huntc** [hseeberger/akka-sse#66]
`WithHeartbeats` performs a `mergePreferred` with default values meaning that the stream will close once all of its inputs have. I'm wondering if `eagerClose=true` might be the preferred option here though - i.e. the heartbeat ticks will likely never close, but if the preferred input closing then you want to tear down the stream. WDYT?

**Comment by hseeberger** [comment]
Have you seen https://github.com/hseeberger/akka-sse/pull/64? Are you using v1.4.2?

**Comment by huntc** [comment]
Oh whoops. Sorry!
