### ISSUE TITLE
Use keepAlive instead of via WithHeartbeats?

### ISSUE THREAD

**Issue by huntc** [hseeberger/akka-sse#67]
@drewhk Told me this wonderful way of emitting heartbeats for Akka streams 2:

```
serviceEventSource
  .map(serviceEvent => ServerSentEventProtocol.serviceEventToServerSentEvent(serviceEvent))
  .keepAlive(heartbeatInterval, () => ServerSentEvent.heartbeat)
```

Should this become the preferred method?

**Comment by hseeberger** [comment]
Very nice! We should definitely use that.

**Comment by drewhk** [comment]
there are various other timeout related methods that have been added including first element timeout, completion timeout, idle-timeout, bidirectional idle-timeout.

**Comment by hseeberger** [comment]
Nice!
