### ISSUE TITLE
Closing the connection from the client-side

### ISSUE THREAD

**Issue by phoenecke** [hseeberger/akka-sse#68]
Based on the client-side usage example:

```
Source.single(Get())
    .via(Http().outgoingConnection("127.0.0.1", 8000))
    .mapAsync(1)(Unmarshal(_).to[Source[ServerSentEvent, Any]])
    .runForeach(_.runForeach(event => println(s"${LocalTime.now()} $event")))
```

What is the proper way to close the connection and stop the stream from the client-side?

**Comment by hseeberger** [comment]
I don't fully understand the question: This stream is materialized via the `runForeach` call. It's source is one that produces a single element only and then signals completion. Hence the stream completes itself.

**Comment by phoenecke** [comment]
Thanks for the response.  I am very new to akka streams...  Maybe "stop the stream" is not the right way to put it.  

I have an actor receiving server-sent events (including `keep-alive` events) like this:

```
Source.single(Get())
    .via(Http().outgoingConnection("127.0.0.1", 8000))
    .mapAsync(1)(Unmarshal(_).to[Source[ServerSentEvent, Any]])
    .runForeach(_.runWith(Sink.actorRef(self, "")))
```

At some point, I would like the actor to stop receiving the server-sent events.  The only way I have found so far is to actually `context.stop(self)` the actor, but I am not sure if that is the right thing to do.

**Comment by hseeberger** [comment]
The ScalaDocs for `Sink.actorRef` say "If the target actor terminates the stream will be canceled.": Hence your approach sounds reasonable (in particular because it's very simple) at least if it's the actor's only purpose to receive these events.
