### ISSUE TITLE
Remove unnecessary and erroneous case in LineParser

### ISSUE THREAD

**Issue by hseeberger** [hseeberger/akka-sse#78]
@viktorklang misinterpreted the previous implementation – which indeed is much harder to comprehend than the Klangonian one – of `parseLines` and added an unnecessary case:

``` scala
case CR if buffer(math.max(at - 1, 0)) == LF => // Ignore first CR after a CRLF sequence
  parseLines(buffer, at + 1, at + 1, parsedLines)
```

Actually a CR after a CRLF is absolutely valid – even if it doesn't make a lot of sense for the domain – and hence the above case not only unnecessary but even erroneous.

**Comment by viktorklang** [comment]
That makes for an even simpler implementation :)

-- 
Cheers,
√
