### ISSUE TITLE
Add an advanced SSE client example  

### ISSUE THREAD

**Issue by Antwnis** [hseeberger/akka-sse#96]
Currently just one example is documented for **client-side**:

```
.via(Http().outgoingConnection("127.0.0.1", 8000))
```

What if i want to subscribe to a SSE, let's say Marathon's [event-stream](https://mesosphere.github.io/marathon/docs/rest-api.html#event-stream)

I'm trying 

```
Source
  .single(
    HttpRequest(uri = "https://marathonserver.xxx.com/v2/events", method = HttpMethods.GET)
      .withHeaders(RawHeader("Accept", "text/event-stream"))
      .withHeaders(Authorization(HttpCredentials.createBasicHttpCredentials("user", "pass")))
  )
  //.via(Http().outgoingConnectionHttps("marathonserver.xxx.com"))
  .mapAsync(1) { c => println(c)
    Unmarshal(c).to[Source[ServerSentEvent, Any]]
  }
  .runForeach(x => { println("1" + x)
    x.runForeach(event => println(s"${LocalTime.now()} $event")) })
```

As you can see i have a number of challenges : https | custom url | basic auth | potentially i should allow unsafe SSL

How would you approach this ?

With **curl** this is just too easy:

```
curl --user user:pass https://marathonserver.xxx.com/v2/events -H "Accept: text/event-stream"
```

**Comment by hseeberger** [comment]
HTTPS, authentication, etc. are not directly related to Akka SSE, but instead are provided by "plain" Akka HTTP. Hence I suggest you ask on the Akka mailing list or Gitter channel.

**Comment by Antwnis** [comment]
import EventStreamUnmarshalling._
    ...
    Source.single(Get())
    .via(Http().outgoingConnection("127.0.0.1", 8000))
    .mapAsync(1)(Unmarshal(_).to[Source[ServerSentEvent, Any]])
    .runForeach(_.runForeach(event => println(s"${LocalTime.now()} $event")))

I'll keep looking & asking - but an example that would demonstrate how to connect to a remote end-point like:

    http://marathon.xxx.com/v2/events

Would be quite nice

**Comment by ognjetina** [comment]
@Antwnis could you please review your links in your posts? :)
