### ISSUE TITLE
Higher level flow abstraction for managing an SSE client connection

### ISSUE THREAD

**Issue by huntc** [hseeberger/akka-sse#99]
I've found myself repeating the following pattern and so I'm wondering if it'd be useful to develop a higher level abstraction to look after SSE client connectivity:

```scala
    Source
      .single(someRequest)
      .via(someConnection)
      .alsoTo(
        Sink.head.mapMaterializedValue(_.foreach { response =>
          if (response.status.isSuccess())
            doSomethingGivenFirstResponse(response)
        })
      )
      .mapAsync(1) { response =>
        Unmarshal(response)
          .to[Source[ServerSentEvent, Any]]
          .flatMap { sseSource =>
            sseSource
              .filter(_.data != "") // Filter out heartbearts
              .runForeach(doSomethingForeachResponse)
          }
      }
      .runWith(
        Sink.onComplete {
          case outcome => doSomethingWithOutcome(outcome)
        }
      )
```

On the event stream having been successfully established, `doSomethingGivenFirstResponse(response: HttpResponse)` is called.

Each SSE element is then subsequently processed via `doSomethingForeachResponse(sse: ServerSentEvent)`. Finally, `doSomethingWithOutcome(outcome: Try[Done])` is called once the stream is terminated - you typically want to re-establish the connection at that point. Perhaps the unmaterialised flow should be returned instead though i.e. drop the `runWith`, thus the flow represents the blueprint.

WDYT? Would you be interested in my devising this higher level flow abstraction? Have you had similar thoughts?

**Comment by huntc** [comment]
Perhaps the above also helps with https://github.com/hseeberger/akka-sse/issues/96

**Comment by hseeberger** [comment]
@huntc, could you please point us to some references (the spec, preferably) which explain that/why SSE should be primarily used as a signalling mechanism?

As far as I'm concerned, I think that conveying proper payloads instead of signals is a valid use case, in particular when used in combination with event ids. For me the latter is a very important aspect of any usage or abstraction on the client side which needs to make sure to neither miss nor receive duplicate events.

**Comment by huntc** [comment]
Here's a reference to the spec: https://html.spec.whatwg.org/multipage/comms.html#server-sent-events

> Event streams are always decoded as UTF-8. There is no way to specify another character encoding.

That means strings only. You have no specified means of conveying the type of payload.

**Comment by hseeberger** [comment]
For me that does not at all indicate that one should not convey "real" data via SSE. Of course the payload has to be serialized into a suitable text format.

**Comment by huntc** [comment]
The data component is effective `text/plain` from a MIME type perspective. You should not interpret it as anything else. This then means that the data is stringly typed. There's no way that you can interpret that data as anything else with surety.

You could argue that SSE lacks a Content-Type field that declares the nature of the data component.

**Comment by hseeberger** [comment]
I disagree.

SSE does have a well defined media/content type: text/event-stream. And the specification dictates how to interpret it, see https://www.w3.org/TR/eventsource/#event-stream-interpretation. Of course one should not interpret it differently.

You'll notice that the data field(s) of a SSE event are used to effectively populate the data property of a client side MessageEvent, see https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent. There's no notion of media/content type at that level any more, hence one is free to interpret the data as needed. Notice that the specification for MessageEvent explicitly refers to strings and blobs.

I think you are confusing the interpretation of SSE (transforming it into client side events/objects) and further consuming/processing these. In my opinion it's perfectly fine to interpret the data of a MessageEvent (in the browser) or of a ServerSentEvent (in the case of akka-sse on the client) – let's say – as JSON.

**Comment by huntc** [comment]
I've missed these discussions. :-)

> In my opinion it's perfectly fine to interpret the data of a MessageEvent (in the browser) or of a ServerSentEvent (in the case of akka-sse on the client) – let's say – as JSON.

So why shouldn't an HTTP GET always just return a string then as opposed to declaring the `Content-Type` of its data? 

To me, the treatment of an event's data is akin to the treatment of a regular HTTP GET's data, particularly when considering multipart where each part declares its content type.

**Comment by hseeberger** [comment]
Me, too ;-)

We agree that in HTTP each response should declare its `Content-Type`. But consuming SSE means:

- first consuming the HTTP response where `Content-Type: text/event-stream` is used and client side events are created
- second applying the client side events in an application specific manner; these events are no longer in HTTP land and there's no notion of content types any more; here one is free to and has to interpret the data property as appropriate

**Comment by huntc** [comment]
> these events are no longer in HTTP land and there's no notion of content types any more; here one is free to and has to interpret the data property as appropriate

Hmm. I think that is where I disagree ie "no notion of content types". Why not? (put http aside, MIME types are used outside of http of course)

**Comment by hseeberger** [comment]
Well, then we have to agree to disagree, because in my every day work I rarely use content types, mime types or other concepts from the realm of HTTP outside of HTTP.

**Comment by huntc** [comment]
I'll withdraw my statement that SSE was designed as a signalling mechanism. That was just my interpretation. However using it as a signalling mechanism aka UNIX signals (limited IPC) is still useful.

Even when not being used for signalling, you must still manage a connection. The abstraction that I proposed helps there. It also helps by filtering out heartbeats. 

Do you see any value in this higher level abstraction?

**Comment by hseeberger** [comment]
Thanks for the great discussion!

I definitely see value in some higher level abstraction. The use cases I have need to reestablish the request (connection) including setting the event id, i.e. are a little different from this one, but anyway, I'd appreciate any energy spent on improving this project. So yes, let's go for it. Maybe in a `pattern` subpackage like in Akka?

**Comment by huntc** [comment]
Good idea - I'll work on this toward the end of the week.
